### ISSUE TITLE
Spurious padding in code blocks

### ISSUE THREAD

**Issue by ineol** [ocaml-sf/learn-ocaml#186]
The first line of blocks of code is padded twice as much as the other lines. I checked in chrome and firefox. I think this is because the rule 
```css
code, pre {
  padding: 0px 4px;
  background: #ddd;
  border-radius: 4px;
}
```
applies twice I think .

![indentation](https://user-images.githubusercontent.com/37965/47283796-0bfa9a00-d5e5-11e8-90f0-2bf1ff7a6946.png)
