### ISSUE TITLE
Exercise header overflows

### ISSUE THREAD

**Issue by ulugbekna** [ocaml-sf/learn-ocaml#374]
A part text in the exercise header, when wrapped, overlays some other part of the headers. 

![image](https://user-images.githubusercontent.com/16353531/103629044-a1ce3580-4f61-11eb-8c22-67c235d2ea91.png)

I noticed that if I disable the `line-height` css style for the header in chrome dev tools, the problem is gone. 

```css
body {
  line-height: 18px /* uncheck */
} 
```
